# test = standard + 2 * JND_LL
# Discarded
stimulus_0:
  label: hue_35p
  noise_condition: H-H
  standard: 135
  test: 157.7
  hue_range:
  - 105
  - 165
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: -15.0
  minVal: -50.0
  maxVal: -1.0
  nUp: 1
  nDown: 2
  stepSizes: 1.0
  nReversals: 3