stimulus_0:
  label: hue_11p
  stairDirection: 1.0
  noise_condition: L-L
  standard: 90.0
  width: 0.0
  hue_range:
  - 60.0
  - 120.0
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 5.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  - 0.5
  nReversals: 2
stimulus_1:
  label: hue_11m
  stairDirection: -1.0
  noise_condition: L-L
  standard: 90.0
  width: 0.0
  hue_range:
  - 60.0
  - 120.0
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 5.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  - 0.5
  nReversals: 2
stimulus_2:
  label: hue_15p
  stairDirection: 1.0
  noise_condition: L-L
  standard: 270.0
  width: 0.0
  hue_range:
  - 240.0
  - 300.0
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 5.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  - 0.5
  nReversals: 2
stimulus_3:
  label: hue_15m
  stairDirection: -1.0
  noise_condition: L-L
  standard: 270.0
  width: 0.0
  hue_range:
  - 240.0
  - 300.0
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 5.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  - 0.5
  nReversals: 2
