stimulus_0:
  label: hue_12p
  stairDirection: 1.0
  noise_condition: L-L
  standard: 135.0
  width: 0.0
  hue_range:
  - 105.0
  - 165.0
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 5.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  - 0.5
  nReversals: 2
stimulus_1:
  label: hue_12m
  stairDirection: -1.0
  noise_condition: L-L
  standard: 135.0
  width: 0.0
  hue_range:
  - 105.0
  - 165.0
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 5.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  - 0.5
  nReversals: 2
stimulus_2:
  label: hue_16p
  stairDirection: 1.0
  noise_condition: L-L
  standard: 315.0
  width: 0.0
  hue_range:
  - 285.0
  - 345.0
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 5.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  - 0.5
  nReversals: 2
stimulus_3:
  label: hue_16m
  stairDirection: -1.0
  noise_condition: L-L
  standard: 315.0
  width: 0.0
  hue_range:
  - 285.0
  - 345.0
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 5.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  - 0.5
  nReversals: 2
