stimulus_0:
  label: hue_3m
  stairDirection: -1.0
  noise_condition: L-H
  standard: 112.5
  width: 24.5
  hue_range:
  - 82.5
  - 142.5
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 10.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  nReversals: 0
stimulus_1:
  label: hue_7m
  stairDirection: -1.0
  noise_condition: L-H
  standard: 292.5
  width: 24.5
  hue_range:
  - 262.5
  - 322.5
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 10.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  nReversals: 0
stimulus_2:
  label: hue_3p
  stairDirection: 1.0
  noise_condition: L-H
  standard: 112.5
  width: 24.5
  hue_range:
  - 82.5
  - 142.5
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 10.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  nReversals: 0
stimulus_3:
  label: hue_7p
  stairDirection: 1.0
  noise_condition: L-H
  standard: 292.5
  width: 24.5
  hue_range:
  - 262.5
  - 322.5
  hue_num: 45
  stairType: simple
  stepType: lin
  startVal: 10.0
  minVal: 0.5
  maxVal: 20.0
  nUp: 1
  nDown: 2
  stepSizes:
  - 2.0
  - 1.0
  nReversals: 0
